2025-06-16 17:51:22,231 INFO    MainThread:15012 [wandb_setup.py:_flush():67] Current SDK version is 0.19.9
2025-06-16 17:51:22,231 INFO    MainThread:15012 [wandb_setup.py:_flush():67] Configure stats pid to 15012
2025-06-16 17:51:22,231 INFO    MainThread:15012 [wandb_setup.py:_flush():67] Loading settings from C:\Users\samue\.config\wandb\settings
2025-06-16 17:51:22,231 INFO    MainThread:15012 [wandb_setup.py:_flush():67] Loading settings from C:\Users\samue\OneDrive\Desktop\MLDL\RL_tesla_project\wandb\settings
2025-06-16 17:51:22,231 INFO    MainThread:15012 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-06-16 17:51:22,231 INFO    MainThread:15012 [wandb_init.py:setup_run_log_directory():662] Logging user logs to C:\Users\samue\OneDrive\Desktop\MLDL\RL_tesla_project\wandb\run-20250616_175122-h2m1v3k4\logs\debug.log
2025-06-16 17:51:22,231 INFO    MainThread:15012 [wandb_init.py:setup_run_log_directory():663] Logging internal logs to C:\Users\samue\OneDrive\Desktop\MLDL\RL_tesla_project\wandb\run-20250616_175122-h2m1v3k4\logs\debug-internal.log
2025-06-16 17:51:22,247 INFO    MainThread:15012 [wandb_init.py:init():781] calling init triggers
2025-06-16 17:51:22,247 INFO    MainThread:15012 [wandb_init.py:init():786] wandb.init called with sweep_config: {}
config: {'_wandb': {'code_path': 'code/train_sac.py'}}
2025-06-16 17:51:22,247 INFO    MainThread:15012 [wandb_init.py:init():809] starting backend
2025-06-16 17:51:22,247 INFO    MainThread:15012 [wandb_init.py:init():813] sending inform_init request
2025-06-16 17:51:22,298 INFO    MainThread:15012 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=spawn, using: spawn
2025-06-16 17:51:22,299 INFO    MainThread:15012 [wandb_init.py:init():823] backend started and connected
2025-06-16 17:51:22,300 INFO    MainThread:15012 [wandb_init.py:init():915] updated telemetry
2025-06-16 17:51:22,385 INFO    MainThread:15012 [wandb_init.py:init():939] communicating run to backend with 90.0 second timeout
2025-06-16 17:51:24,102 INFO    MainThread:15012 [wandb_init.py:init():1014] starting run threads in backend
2025-06-16 17:51:24,646 INFO    MainThread:15012 [wandb_run.py:_console_start():2454] atexit reg
2025-06-16 17:51:24,647 INFO    MainThread:15012 [wandb_run.py:_redirect():2306] redirect: wrap_raw
2025-06-16 17:51:24,647 INFO    MainThread:15012 [wandb_run.py:_redirect():2371] Wrapping output streams.
2025-06-16 17:51:24,647 INFO    MainThread:15012 [wandb_run.py:_redirect():2394] Redirects installed.
2025-06-16 17:51:24,651 INFO    MainThread:15012 [wandb_init.py:init():1056] run started, returning control to user process
2025-06-16 17:51:28,134 INFO    MainThread:15012 [wandb_run.py:_tensorboard_callback():1524] tensorboard callback: ./tb_logs/SAC_1, True
2025-06-16 17:51:28,205 INFO    MainThread:15012 [wandb_run.py:_config_callback():1327] config_cb None None {'algo': 'SAC', 'policy_class': "<class 'stable_baselines3.sac.policies.SACPolicy'>", 'device': 'cuda', 'verbose': 1, 'policy_kwargs': "{'use_sde': False}", 'num_timesteps': 0, '_total_timesteps': 1000000, '_num_timesteps_at_start': 0, 'seed': 'None', 'action_noise': 'None', 'start_time': 1750089087520276100, 'learning_rate': 0.0003, 'tensorboard_log': './tb_logs/', '_last_obs': '[[-4.4444445e-01 -4.4444445e-01  1.6735790e-02  4.9896628e-02\n   1.3680905e+00  6.5793018e-03 -3.5741639e-03  9.9997199e-01\n   6.7911357e-01  1.0000000e+00  1.0000000e+00  1.0000000e+00\n   1.0000000e+00  1.0000000e+00  1.0000000e+00  1.0000000e+00\n   1.0000000e+00  1.0000000e+00  8.2037944e-01  1.0000000e+00\n   1.0000000e+00  1.0000000e+00  1.0000000e+00  1.0000000e+00\n   1.0000000e+00  1.0000000e+00  1.0000000e+00  8.3890373e-01\n   6.9881284e-01  3.3663819e-04 -5.2449461e-02  6.7910582e-01]]', '_last_episode_starts': '[ True]', '_last_original_obs': 'None', '_episode_num': 0, 'use_sde': 'False', 'sde_sample_freq': -1, '_current_progress_remaining': 1.0, '_stats_window_size': 100, 'ep_info_buffer': 'deque([], maxlen=100)', 'ep_success_buffer': 'deque([], maxlen=100)', '_n_updates': 0, '_custom_logger': 'False', 'env': '<stable_baselines3.common.vec_env.dummy_vec_env.DummyVecEnv object at 0x000001FB23532270>', '_vec_normalize_env': 'None', 'observation_space': 'Box(-inf, inf, (32,), float32)', 'action_space': 'Box([-50.  -50.   -0.5], [130.  130.    0.5], (3,), float32)', 'n_envs': 1, 'buffer_size': 1000000, 'batch_size': 256, 'learning_starts': 100, 'tau': 0.005, 'gamma': 0.99, 'gradient_steps': 1, 'optimize_memory_usage': 'False', 'replay_buffer': '<stable_baselines3.common.buffers.ReplayBuffer object at 0x000001FB23446BA0>', 'replay_buffer_class': "<class 'stable_baselines3.common.buffers.ReplayBuffer'>", 'replay_buffer_kwargs': '{}', '_episode_storage': 'None', 'train_freq': "TrainFreq(frequency=1, unit=<TrainFrequencyUnit.STEP: 'step'>)", 'use_sde_at_warmup': 'False', 'target_entropy': -3.0, 'log_ent_coef': "tensor([0.], device='cuda:0', requires_grad=True)", 'ent_coef': 'auto', 'target_update_interval': 1, 'ent_coef_optimizer': 'Adam (\nParameter Group 0\n    amsgrad: False\n    betas: (0.9, 0.999)\n    capturable: False\n    differentiable: False\n    eps: 1e-08\n    foreach: None\n    fused: None\n    lr: 0.0003\n    maximize: False\n    weight_decay: 0\n)', 'lr_schedule': '<function get_schedule_fn.<locals>.<lambda> at 0x000001FB2351FF60>', 'policy': 'SACPolicy(\n  (actor): Actor(\n    (features_extractor): FlattenExtractor(\n      (flatten): Flatten(start_dim=1, end_dim=-1)\n    )\n    (latent_pi): Sequential(\n      (0): Linear(in_features=32, out_features=256, bias=True)\n      (1): ReLU()\n      (2): Linear(in_features=256, out_features=256, bias=True)\n      (3): ReLU()\n    )\n    (mu): Linear(in_features=256, out_features=3, bias=True)\n    (log_std): Linear(in_features=256, out_features=3, bias=True)\n  )\n  (critic): ContinuousCritic(\n    (features_extractor): FlattenExtractor(\n      (flatten): Flatten(start_dim=1, end_dim=-1)\n    )\n    (qf0): Sequential(\n      (0): Linear(in_features=35, out_features=256, bias=True)\n      (1): ReLU()\n      (2): Linear(in_features=256, out_features=256, bias=True)\n      (3): ReLU()\n      (4): Linear(in_features=256, out_features=1, bias=True)\n    )\n    (qf1): Sequential(\n      (0): Linear(in_features=35, out_features=256, bias=True)\n      (1): ReLU()\n      (2): Linear(in_features=256, out_features=256, bias=True)\n      (3): ReLU()\n      (4): Linear(in_features=256, out_features=1, bias=True)\n    )\n  )\n  (critic_target): ContinuousCritic(\n    (features_extractor): FlattenExtractor(\n      (flatten): Flatten(start_dim=1, end_dim=-1)\n    )\n    (qf0): Sequential(\n      (0): Linear(in_features=35, out_features=256, bias=True)\n      (1): ReLU()\n      (2): Linear(in_features=256, out_features=256, bias=True)\n      (3): ReLU()\n      (4): Linear(in_features=256, out_features=1, bias=True)\n    )\n    (qf1): Sequential(\n      (0): Linear(in_features=35, out_features=256, bias=True)\n      (1): ReLU()\n      (2): Linear(in_features=256, out_features=256, bias=True)\n      (3): ReLU()\n      (4): Linear(in_features=256, out_features=1, bias=True)\n    )\n  )\n)', 'actor': 'Actor(\n  (features_extractor): FlattenExtractor(\n    (flatten): Flatten(start_dim=1, end_dim=-1)\n  )\n  (latent_pi): Sequential(\n    (0): Linear(in_features=32, out_features=256, bias=True)\n    (1): ReLU()\n    (2): Linear(in_features=256, out_features=256, bias=True)\n    (3): ReLU()\n  )\n  (mu): Linear(in_features=256, out_features=3, bias=True)\n  (log_std): Linear(in_features=256, out_features=3, bias=True)\n)', 'critic': 'ContinuousCritic(\n  (features_extractor): FlattenExtractor(\n    (flatten): Flatten(start_dim=1, end_dim=-1)\n  )\n  (qf0): Sequential(\n    (0): Linear(in_features=35, out_features=256, bias=True)\n    (1): ReLU()\n    (2): Linear(in_features=256, out_features=256, bias=True)\n    (3): ReLU()\n    (4): Linear(in_features=256, out_features=1, bias=True)\n  )\n  (qf1): Sequential(\n    (0): Linear(in_features=35, out_features=256, bias=True)\n    (1): ReLU()\n    (2): Linear(in_features=256, out_features=256, bias=True)\n    (3): ReLU()\n    (4): Linear(in_features=256, out_features=1, bias=True)\n  )\n)', 'critic_target': 'ContinuousCritic(\n  (features_extractor): FlattenExtractor(\n    (flatten): Flatten(start_dim=1, end_dim=-1)\n  )\n  (qf0): Sequential(\n    (0): Linear(in_features=35, out_features=256, bias=True)\n    (1): ReLU()\n    (2): Linear(in_features=256, out_features=256, bias=True)\n    (3): ReLU()\n    (4): Linear(in_features=256, out_features=1, bias=True)\n  )\n  (qf1): Sequential(\n    (0): Linear(in_features=35, out_features=256, bias=True)\n    (1): ReLU()\n    (2): Linear(in_features=256, out_features=256, bias=True)\n    (3): ReLU()\n    (4): Linear(in_features=256, out_features=1, bias=True)\n  )\n)', 'batch_norm_stats': '[]', 'batch_norm_stats_target': '[]', '_logger': '<stable_baselines3.common.logger.Logger object at 0x000001FB3D35CFB0>'}
2025-06-16 19:51:20,034 INFO    MsgRouterThr:15012 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 1 handles.
2025-06-16 19:51:20,207 ERROR   Thread-11 :15012 [redirect.py:_on_write():661] [no run ID] error in stdout callback
Traceback (most recent call last):
  File "C:\Python312\Lib\site-packages\wandb\sdk\lib\redirect.py", line 659, in _on_write
    cb(written_data)
  File "C:\Python312\Lib\site-packages\wandb\sdk\wandb_run.py", line 2375, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\wandb\sdk\wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\wandb\sdk\wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\wandb\sdk\wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "C:\Python312\Lib\site-packages\wandb\sdk\interface\interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "C:\Python312\Lib\site-packages\wandb\sdk\interface\interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "C:\Python312\Lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "C:\Python312\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "C:\Python312\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "C:\Python312\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Python312\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] Connessione interrotta dal software del computer host
2025-06-16 19:51:20,412 ERROR   Thread-11 :15012 [redirect.py:_on_write():661] [no run ID] error in stdout callback
Traceback (most recent call last):
  File "C:\Python312\Lib\site-packages\wandb\sdk\lib\redirect.py", line 659, in _on_write
    cb(written_data)
  File "C:\Python312\Lib\site-packages\wandb\sdk\wandb_run.py", line 2375, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\wandb\sdk\wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\wandb\sdk\wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\wandb\sdk\wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "C:\Python312\Lib\site-packages\wandb\sdk\interface\interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "C:\Python312\Lib\site-packages\wandb\sdk\interface\interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "C:\Python312\Lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "C:\Python312\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "C:\Python312\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "C:\Python312\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Python312\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] Connessione interrotta dal software del computer host
2025-06-16 19:51:20,540 ERROR   Thread-11 :15012 [redirect.py:_on_write():661] [no run ID] error in stdout callback
Traceback (most recent call last):
  File "C:\Python312\Lib\site-packages\wandb\sdk\lib\redirect.py", line 659, in _on_write
    cb(written_data)
  File "C:\Python312\Lib\site-packages\wandb\sdk\wandb_run.py", line 2375, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\wandb\sdk\wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\wandb\sdk\wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\wandb\sdk\wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "C:\Python312\Lib\site-packages\wandb\sdk\interface\interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "C:\Python312\Lib\site-packages\wandb\sdk\interface\interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "C:\Python312\Lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "C:\Python312\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "C:\Python312\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "C:\Python312\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Python312\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] Connessione interrotta dal software del computer host
2025-06-16 19:51:20,667 ERROR   Thread-11 :15012 [redirect.py:_on_write():661] [no run ID] error in stdout callback
Traceback (most recent call last):
  File "C:\Python312\Lib\site-packages\wandb\sdk\lib\redirect.py", line 659, in _on_write
    cb(written_data)
  File "C:\Python312\Lib\site-packages\wandb\sdk\wandb_run.py", line 2375, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\wandb\sdk\wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\wandb\sdk\wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\wandb\sdk\wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "C:\Python312\Lib\site-packages\wandb\sdk\interface\interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "C:\Python312\Lib\site-packages\wandb\sdk\interface\interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "C:\Python312\Lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "C:\Python312\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "C:\Python312\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "C:\Python312\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Python312\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] Connessione interrotta dal software del computer host
2025-06-16 19:51:20,792 ERROR   Thread-11 :15012 [redirect.py:_on_write():661] [no run ID] error in stdout callback
Traceback (most recent call last):
  File "C:\Python312\Lib\site-packages\wandb\sdk\lib\redirect.py", line 659, in _on_write
    cb(written_data)
  File "C:\Python312\Lib\site-packages\wandb\sdk\wandb_run.py", line 2375, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\wandb\sdk\wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\wandb\sdk\wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\wandb\sdk\wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "C:\Python312\Lib\site-packages\wandb\sdk\interface\interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "C:\Python312\Lib\site-packages\wandb\sdk\interface\interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "C:\Python312\Lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "C:\Python312\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "C:\Python312\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "C:\Python312\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Python312\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] Connessione interrotta dal software del computer host
2025-06-16 19:51:20,935 ERROR   Thread-11 :15012 [redirect.py:_on_write():661] [no run ID] error in stdout callback
Traceback (most recent call last):
  File "C:\Python312\Lib\site-packages\wandb\sdk\lib\redirect.py", line 659, in _on_write
    cb(written_data)
  File "C:\Python312\Lib\site-packages\wandb\sdk\wandb_run.py", line 2375, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\wandb\sdk\wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\wandb\sdk\wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\wandb\sdk\wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "C:\Python312\Lib\site-packages\wandb\sdk\interface\interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "C:\Python312\Lib\site-packages\wandb\sdk\interface\interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "C:\Python312\Lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "C:\Python312\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "C:\Python312\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "C:\Python312\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Python312\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] Connessione interrotta dal software del computer host
2025-06-16 19:51:21,068 ERROR   Thread-11 :15012 [redirect.py:_on_write():661] [no run ID] error in stdout callback
Traceback (most recent call last):
  File "C:\Python312\Lib\site-packages\wandb\sdk\lib\redirect.py", line 659, in _on_write
    cb(written_data)
  File "C:\Python312\Lib\site-packages\wandb\sdk\wandb_run.py", line 2375, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\wandb\sdk\wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\wandb\sdk\wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\wandb\sdk\wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "C:\Python312\Lib\site-packages\wandb\sdk\interface\interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "C:\Python312\Lib\site-packages\wandb\sdk\interface\interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "C:\Python312\Lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "C:\Python312\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "C:\Python312\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "C:\Python312\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Python312\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] Connessione interrotta dal software del computer host
2025-06-16 19:51:21,176 ERROR   Thread-11 :15012 [redirect.py:_on_write():661] [no run ID] error in stdout callback
Traceback (most recent call last):
  File "C:\Python312\Lib\site-packages\wandb\sdk\lib\redirect.py", line 659, in _on_write
    cb(written_data)
  File "C:\Python312\Lib\site-packages\wandb\sdk\wandb_run.py", line 2375, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\wandb\sdk\wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\wandb\sdk\wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\wandb\sdk\wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "C:\Python312\Lib\site-packages\wandb\sdk\interface\interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "C:\Python312\Lib\site-packages\wandb\sdk\interface\interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "C:\Python312\Lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "C:\Python312\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "C:\Python312\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "C:\Python312\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Python312\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] Connessione interrotta dal software del computer host
2025-06-16 19:51:21,281 ERROR   Thread-11 :15012 [redirect.py:_on_write():661] [no run ID] error in stdout callback
Traceback (most recent call last):
  File "C:\Python312\Lib\site-packages\wandb\sdk\lib\redirect.py", line 659, in _on_write
    cb(written_data)
  File "C:\Python312\Lib\site-packages\wandb\sdk\wandb_run.py", line 2375, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\wandb\sdk\wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\wandb\sdk\wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\wandb\sdk\wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "C:\Python312\Lib\site-packages\wandb\sdk\interface\interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "C:\Python312\Lib\site-packages\wandb\sdk\interface\interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "C:\Python312\Lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "C:\Python312\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "C:\Python312\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "C:\Python312\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Python312\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] Connessione interrotta dal software del computer host
2025-06-16 19:51:21,393 ERROR   Thread-11 :15012 [redirect.py:_on_write():661] [no run ID] error in stdout callback
Traceback (most recent call last):
  File "C:\Python312\Lib\site-packages\wandb\sdk\lib\redirect.py", line 659, in _on_write
    cb(written_data)
  File "C:\Python312\Lib\site-packages\wandb\sdk\wandb_run.py", line 2375, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\wandb\sdk\wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\wandb\sdk\wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\wandb\sdk\wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "C:\Python312\Lib\site-packages\wandb\sdk\interface\interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "C:\Python312\Lib\site-packages\wandb\sdk\interface\interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "C:\Python312\Lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "C:\Python312\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "C:\Python312\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "C:\Python312\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Python312\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] Connessione interrotta dal software del computer host
2025-06-16 19:51:21,406 ERROR   MainThread:15012 [redirect.py:_on_write():661] [no run ID] error in stdout callback
Traceback (most recent call last):
  File "C:\Python312\Lib\site-packages\wandb\sdk\lib\redirect.py", line 659, in _on_write
    cb(written_data)
  File "C:\Python312\Lib\site-packages\wandb\sdk\wandb_run.py", line 2375, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\wandb\sdk\wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\wandb\sdk\wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\wandb\sdk\wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "C:\Python312\Lib\site-packages\wandb\sdk\interface\interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "C:\Python312\Lib\site-packages\wandb\sdk\interface\interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "C:\Python312\Lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "C:\Python312\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "C:\Python312\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "C:\Python312\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Python312\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] Connessione interrotta dal software del computer host
